export const CITY = "CITY";
export const FETCHING_CURRENT_WEATHER = "FETCHING_CURRENT_WEATHER";
export const GET_CURRENT_WEATHER = "GET_CURRENT_WEATHER";
export const ERROR_CURRENT_WEATHER = "ERROR_CURRENT_WEATHER";
export const FETCHING_FORECAST = "FETCHING_FORECAST";
export const ERROR_FORECAST = "ERROR_FORECAST";
export const GET_FORECAST = "GET_FORECAST";